# Build .NET Framework 3.5 projects

trigger:
- main

pool:
  # vmImage: 'vs2017-win2016'
  # name: 'Hosted'
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: 'vs2017-win2016'
  displayName: 'vs2017-win2016 image'

  pool:
    # vmImage: 'vs2017-win2016'
    # name: 'Hosted'
    vmImage: 'windows-2019'

  steps:
  - template: ./dotnet-framework35-steps.yml